-- Example schema (run in Supabase SQL editor)

-- 1) Profiles table to store role
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null check (role in ('admin', 'viewer')) default 'viewer',
  created_at timestamptz not null default now()
);

-- 2) Employees
create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  department text not null,
  performance int not null check (performance between 0 and 100),
  competency int not null check (competency between 0 and 100),
  training int not null check (training between 0 and 100)
);

-- 3) Training programs
create table if not exists public.training_programs (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null,
  duration text not null,
  participants int not null default 0,
  status text not null check (status in ('upcoming','ongoing','completed'))
);

-- 4) Competencies
create table if not exists public.competencies (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  category text not null,
  weight int not null
);

-- 5) Recognition awards
create table if not exists public.recognition_awards (
  id bigint generated by default as identity primary key,
  recipient text not null,
  type text not null,
  department text not null,
  date date not null,
  reason text not null
);

-- 6) Succession candidates
-- NOTE: "current_role" is a reserved-ish identifier in some contexts, so quote it.
create table if not exists public.succession_candidates (
  id bigint generated by default as identity primary key,
  "current_role" text not null,
  readiness text not null,
  timeline text not null,
  candidates text[] not null default '{}'
);


-- Helpers for RLS
-- Allow admins only for writes
create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;

-- Enable RLS and policies
-- Employees
alter table public.employees enable row level security;
drop policy if exists "employees_select" on public.employees;
create policy "employees_select" on public.employees for select using (true);
-- If you re-run the script, this policy may already exist; drop it first to avoid errors.
drop policy if exists "employees_write_admin" on public.employees;
create policy "employees_write_admin" on public.employees for all using (public.is_admin()) with check (public.is_admin());

-- Training programs
alter table public.training_programs enable row level security;
drop policy if exists "training_select" on public.training_programs;
drop policy if exists "training_write_admin" on public.training_programs;
create policy "training_select" on public.training_programs for select using (true);
create policy "training_write_admin" on public.training_programs for all using (public.is_admin()) with check (public.is_admin());

-- Competencies
alter table public.competencies enable row level security;
drop policy if exists "competencies_select" on public.competencies;
drop policy if exists "competencies_write_admin" on public.competencies;
create policy "competencies_select" on public.competencies for select using (true);
create policy "competencies_write_admin" on public.competencies for all using (public.is_admin()) with check (public.is_admin());

-- Recognition
alter table public.recognition_awards enable row level security;
drop policy if exists "recognition_select" on public.recognition_awards;
drop policy if exists "recognition_write_admin" on public.recognition_awards;
create policy "recognition_select" on public.recognition_awards for select using (true);
create policy "recognition_write_admin" on public.recognition_awards for all using (public.is_admin()) with check (public.is_admin());

-- Succession
alter table public.succession_candidates enable row level security;
drop policy if exists "succession_select" on public.succession_candidates;
drop policy if exists "succession_write_admin" on public.succession_candidates;
create policy "succession_select" on public.succession_candidates for select using (true);
create policy "succession_write_admin" on public.succession_candidates for all using (public.is_admin()) with check (public.is_admin());

